### PR TITLE
Everything seems to be working

### PR DESCRIPTION
**Pull request by robotastic**
This works with the latest version of the Nordic BLE library. Copy the ancs_services.h file into that directory.

I also changed the notification buffer into a static array of struts to prevent the memory fragmentation that might come from all of the Mallocs and frees. I also limited attribute size to 16chars, can scale longer though.

I need to do some more documentation, but I am working on a branch that outputs to an LCD and didn't want to get too far away.

### CODE REVIEW

**Comment by guyzmo** [comment]
I think that you should not call `ancs_services.h` that way, but keep it as `services.h`. As you say "copy it in ble_lib", you may actually want to put that file, along with the .xml it comes with in a new third directory that could be called `contrib/` or `config/` or `service/`.

I think that you could have kept the `malloc()` at least for retrieving the buffer, as for that use case there's no chance of smash. :-)

The commit messages you've done are not really helping for me to understand the work you've done, as they do not represent what you've done within the commit, but only the status you're at. I can guess that you're _improving_, _working it_ out, _progress_ing etc.. :-) What would have been useful is to say stuff like:

```
Refactored code to use external ble_lib and to drop the heap usage
  * removed ble_lib from repository
  * changed notification linked list to static array in ancs lib
  * changed attribute getting buffer to a static array in ancs lib
```

The code you've added that is 100% specific to your project should be included in a separate header file and compilation unit, if needed (I'm thinking of the lcd stuff in the main .ino). That may get confusing for users of the library

Otherwise, if you indeed has it working fine and are happy with it :+1: gg :-)

**Comment by robotastic** [comment]
Cool - I can switch it back to `services.h`. Were you thinking of having that 3rd directory be at the top level or still under `BLE`? 

My commenting / commit messages are horrible, sorry about that. I am bad about checking in more often and when I do, too much stuff is bundled up. I haven't really done much collaborative coding, so my manners need work. It would have made things a lot clearer. I am a convert!

On that point - I only switched the attribute/notification cache to a static array. I left the dynamic buffers for building attribute request buffers since the are allocated and free'd in the same function call.

I have all of the code specific to my project/LCDs in a separate branch. I am active working on that branch. I ported over the useful changes back to the main branch, but accidentally may have brought over something. If you see something that made it over, let me know. I will double check too.

**Comment by robotastic** [comment]
I totally botched the merge. I just double checked and the LCD stuff should not be in the .ino file. I will remove it.

**Comment by robotastic** [comment]
I think I have things fixed up. I moved/renamed the services.h file and removed the remaining LCD related code I missed.

**Comment by guyzmo** [comment]
if you could rename the commits as well, that would be great ;-) To do so, here's some git-fu, about rewriting history:

```
git rebase -i HEAD~10
# change pick for reword on each commit that needs a name change and save and quit
# then for each commit you'll have the editor poping up, and the changes you do and save there will be applied 
git push -f github # given that you call this remote github, and -f is to force the history rewrite push
```

then you can rebase your other repository (for your code with the LCD) on that one, though I think you'd better use it as a submodule.

as a tip, use `GitXR` if you're on OSX, or `meld` if you're on linux to double check your commits changes. On the comments themselves, the good usage (as adviced by Linus himself), is to have a one line summary of the changeset, followed by more details on that changeset as a list.

If you don't have time, or don't want to make the changes, at least you'll learn a bit more about git reading this comment ;-)

**Comment by robotastic** [comment]
Let me give it a shot. I will also try to summarize the useful changes in
each commit. I will also check out submodules. I haven't really played
around with them much. Of course I am doing everything through the OSX
github client. I just got SourceTree and Tower. I am ok with cmdline, but
lazy. I looked for GitXR, but I couldn't find it. Did you mean GitX?

I might try moving some of the functionality from the main.ino to the ancs
lib so things in the main.ino file are a bit cleaner. Of course all of this
is dependent on the kids taking a nap.

**Comment by guyzmo** [comment]
> Let me give it a shot. I will also try to summarize the useful changes in each commit.

great!

> Of course I am doing everything through the OSX github client. I just got SourceTree and Tower. I am ok with cmdline, but lazy.  I looked for GitXR, but I couldn't find it. Did you mean GitX?

I was talking of the rowanj fork of gitx that used to be called gitxr :-)
- https://rowanj.github.io/gitx/

you'll see it's really a life changer.

> I might try moving some of the functionality from the main.ino to the ancs lib so things in the main.ino file are a bit cleaner. Of course all of this is dependent on the kids taking a nap.

great! :+1:

**Comment by robotastic** [comment]
I renamed the commits to make them clearer - hopefully that cleans things up a bit.

GitX (R) is pretty sweet, thanks for the pointer.

I have a GitHub etiquette question. I was planning on doing the cleaned up version as a stand alone fork instead of keeping it in a state where it can be merged back in. I am not sure if I am going to have enough time to get everything commented and documented. It might be sloppy. If the right thing to do is to bring the code back and you are interested, I can try to keep it mergable.

**Comment by guyzmo** [comment]
> I renamed the commits to make them clearer - hopefully that cleans things up a bit.

ok, I'll review all that when I'll get a time slot to focus on it. Thanks for the help :-)

> GitX (R) is pretty sweet, thanks for the pointer.

glad to have helped ;-)

> I have a GitHub etiquette question. I was planning on doing the cleaned up version as a stand alone fork instead of keeping it in a state where it can be merged back in. I am not sure if I am going to have enough time to get everything commented and documented. It might be sloppy. If the right thing to do is to bring the code back and you are interested, I can try to keep it mergable.

Well, it's not a github etiquette question, it's more about what attitude you want to get against a FLOSS project. You've sent patches to improve the work I published, I'll be happy to integrate them once I'll have reviewed them all, and so offer to everybody the best AVR/nRF/ANCS library possible :-). So, my opinion, is that you should integrate that library like you were integrating any other external library you were downloading from Internet in your project(s) and get on working and improving it as you're using it. 

Once your changes will be integrated, I'll add you to the project's "team" ;-).

**Comment by robotastic** [comment]
Cool - Github seems a lot more Fork friendly compared to older sites like Freshmeat. I am happy to contribute back what I come up with... and will try to document my commits! :)

I am starting a new job in 2 weeks and will starting being really busy, so I have that as a deadline to have things wrapped up as best as possible and to put together a tutorial.

I have already started to get things integrated and the Arduino IDE is a pain. It's default compile flags make some of the imports a bit messy. I have managed to get it to compile though.

**Comment by robotastic** [comment]
I think  I have everything wrapped up for the arduino library. I don't have much more time to work on it, but I will keep trying to make small tweaks.

**Pull request merged**
